config/routes.rb
Rails.application.routes.draw do
  root 'stats#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: :create
      resources :messages, only: %i[index create] do
        resources :votes, only: :create
        get :search, on: :collection
      end
      post 'user_token' => 'user_token#create'
    end
  end
  resources :stats, only: :index
end

app/models/application_record.rb
# http://blog.bigbinary.com/2015/12/28/application-record-in-rails-5.html
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# Message model
class Message < ApplicationRecord
  searchkick
  PAGE_SIZE = 10

  paginates_per PAGE_SIZE

  validates :text, presence: true,
                   length: { minimum: 8, maximum: 140 }

  belongs_to :user, counter_cache: :count_of_messages
  has_many :votes

  scope :by_create_time, -> { order(created_at: :desc) }

  def self.in_time_range(range)
    if range == 'week'
      Message.where(created_at: 1.week.ago..Time.zone.now)
    elsif range == 'day'
      Message.where(created_at: 1.day.ago..Time.zone.now)
    else
      Message.all
    end
  end
end

app/models/statistic_query.rb
# Class for complex SQL queries
class StatisticQuery
  def initialize(relation = Message.all)
    @relation = relation
  end

  def top_writers
    columns = 'users.nickname, users.count_of_messages'
    order_rule = 'users.count_of_messages DESC'

    relation.joins(:user).select(columns).order(order_rule).limit(5).distinct
  end

  def top_popular
    columns = 'users.id,users.nickname,messages.text,messages.count_of_votes'
    order_rule = 'messages.count_of_votes DESC'

    relation.joins(:user).select(columns).order(order_rule).limit(5)
  end

  def top_avg
    columns = 'users.id,users.nickname,AVG(messages.count_of_votes) as rating'
    group = 'users.id'
    order = 'rating DESC'

    relation.joins(:user).select(columns).group(group).order(order).limit(5)
  end

  private

  attr_reader :relation
end

app/models/user.rb
# User model
class User < ApplicationRecord
  has_secure_password

  has_many :messages, dependent: :destroy

  # http://www.aidanf.net/posts/validating-emails-in-rails
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  validates :email,    presence: true, uniqueness: { case_sensitive: false },
                       format: { with: EMAIL_REGEX }
  validates :nickname, presence: true, uniqueness: { case_sensitive: false },
                       length: { minimum: 8, maximum: 32 }
  validates :password, presence: true, length: { minimum: 8 }, on: :create
end

app/models/vote.rb
# Vote model
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :message, counter_cache: :count_of_votes
  validates :message, uniqueness: { scope: :user_id }
end

app/controllers/api/v1/api_controller.rb
module Api
  module V1
    # Base API Controller
    class ApiController < ActionController::API
      include Knock::Authenticable

      def render_errors(obj, status: :unprocessable_entity)
        render json: { errors: obj.errors }, status: status
      end
    end
  end
end

app/controllers/api/v1/messages_controller.rb
module Api
  module V1
    # Controller for creating messages
    # Authentication required
    class MessagesController < ApiController
      before_action :authenticate_user, only: :create

      def index
        messages = Message.by_create_time.page(params[:page]).includes(:user)

        response.headers['X-Total-Pages-Count'] = messages.total_pages
        render json: messages
      end

      def search
        messages = Message.search(
          params[:query],
          page: params[:page],
          per_page: Message::PAGE_SIZE
        )
        
        render json: messages
      end

      def create
        message = current_user.messages.build(message_params)

        if message.save
          render json: message, status: :created
        else
          render_errors(message)
        end
      end

      def message_params
        params.require(:message).permit(:text)
      end
    end
  end
end

app/controllers/api/v1/user_token_controller.rb
module Api
  module V1
    class UserTokenController < Knock::AuthTokenController; end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    # Controller for actions with users
    class UsersController < ApiController
      def create
        user = User.new(user_params)
        if user.save
          head :created
        else
          render_errors(user)
        end
      end

      def user_params
        params.require(:user).permit(:email, :password, :nickname)
      end
    end
  end
end

app/controllers/api/v1/votes_controller.rb
module Api
  module V1
    # Controller for messages voting
    # Authentication required
    class VotesController < ApiController
      before_action :authenticate_user
      before_action :set_message

      def create
        vote = Vote.new(user: current_user, message: @message)

        if vote.save
          head :created
        else
          render_errors(vote)
        end
      end

      def set_message
        @message = Message.find(params[:message_id])
      end
    end
  end
end

app/controllers/application_controller.rb
# Base controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stats_controller.rb
# Controller for showing service statistics
class StatsController < ApplicationController
  def index
    query_object = StatisticQuery.new(
      Message.in_time_range(params[:range])
    )

    @top_writers = query_object.top_writers
    @top_popular = query_object.top_popular
    @top_avg     = query_object.top_avg
  end
end

app/helpers/application_helper.rb
# http://api.rubyonrails.org/classes/ActionController/Helpers.html
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Service Statistics</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stats/_avg.html.slim
h1 Writers by AVG rating
table.table-bordered
  th Nickname
  th Avg Rating
  - top_avg.each do |tw|
    tr
      td
        = tw.nickname
      td
        = tw.rating.round(3)

app/views/stats/_links.html.slim
  ul.list-inline
    li.list-group-item
      == link_to 'All',  stats_path
    li.list-group-item
      == link_to 'Day',  stats_path({ range: 'day' })
    li.list-group-item
      == link_to 'Week', stats_path({ range: 'week' })

app/views/stats/_popular.html.slim
h1 Popular
table.table-bordered align="center"
  th Nickname
  th Message text
  th Votes count
  - top_popular.each do |tw|
    tr
      td
        = tw.nickname
      td
        = tw.text
      td
        = tw.count_of_votes

app/views/stats/_top_writers.html.slim
h1 Top Writers
table.table-bordered align="center"
  th Nickname
  th Messages
  - top_writers.each do |tw|
    tr
      td
        = tw.nickname
      td
        = tw.count_of_messages

app/views/stats/index.html.slim
.container align="center"
  .col-md-4.col-md-offset-4.col-lg-4.col-lg-offset-4.col-sm-4.col-sm-offset-4.col-xs-4.col-xs-offset-4
    == render 'links'
  .col-md-4.col-md-offset-4.col-lg-4.col-lg-offset-4.col-sm-6.col-sm-offset-3.col-xs-8.col-xs-offset-2

    == render 'top_writers', { top_writers: @top_writers }
    == render 'popular'    , { top_popular: @top_popular }
    == render 'avg'        , { top_avg:     @top_avg     }